#!/bin/bash
### BEGIN INIT INFO
# Provides:          chrome-remote-desktop-patch
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Chrome remote desktop patch
# Description:       Chrome remote desktop patch for running DISPLAY:0
### END INIT INFO

TARGET=/opt/google/chrome-remote-desktop/chrome-remote-desktop
TARGETBACKUP=/opt/google/chrome-remote-desktop/chrome-remote-desktop.original

if ! grep -q '^DEFAULT_SIZES = "1920x1080"' $TARGET; then
  cp $TARGET $TARGETBACKUP
  sed -i 's/^DEFAULT_SIZES = "*/#&/g' $TARGET
  sed -i '/^#DEFAULT_SIZES/a DEFAULT_SIZES = "1920x1080"' $TARGET
fi

if ! grep -q '^FIRST_X_DISPLAY_NUMBER = 0' $TARGET; then
  sed -i 's/^FIRST_X_DISPLAY_NUMBER = */#&/g' $TARGET
  sed -i '/^#FIRST_X_DISPLAY_NUMBER/a FIRST_X_DISPLAY_NUMBER = 0' $TARGET
fi

sed -i 's/^    while os.path.exists(X_LOCK_FILE_TEMPLATE % display):*/#&/g' $TARGET
sed -i 's/^      display += 1*/#&/g' $TARGET

sed -i 's/^    self._launch_server(server_args)*/#&/g' $TARGET
sed -i 's/^    self._launch_x_server(x_args)*/#&/g' $TARGET
sed -i 's/^    if not self._launch_pre_session():*/#&/g' $TARGET
sed -i 's/^      self.launch_desktop_session()*/#&/g' $TARGET
if ! grep -q 'display = self.get_unused_display_number()#' $TARGET; then
  sed -i '/^#      self.launch_desktop_session()/a \ \ \ \ display = self.get_unused_display_number()#\n\ \ \ \ self.child_env[\x27DISPLAY\x27] = f\x27:{display}\x27#' $TARGET
