#!/bin/bash

cd /home/user/.nvm
source nvm.sh

cd /opt/jupyterhub_venv
source bin/activate

cd /opt/jupyterhub
cd /opt/jupyterhub_venv/bin/jupyterhub -f /opt/jupyterhub/etc/jupyterhub/jupyterhub_config.py
